import { Router } from 'express'; import bcrypt from 'bcryptjs'; import { z } from 'zod'; import { prisma } from '../lib/prisma.js'; import { auth, permit } from '../middleware/auth.js'; import { audit } from '../services/audit.js';
const r=Router(); r.use(auth);

r.post('/staff',permit('staff.write'),async(req,res)=>{const p=z.object({email:z.string().email(),firstName:z.string(),lastName:z.string(),phone:z.string().optional(),officeId:z.string().optional(),title:z.string(),department:z.string(),roleName:z.string().default('OFFICE_STAFF')}).parse(req.body);let role=await prisma.role.findUnique({where:{name:p.roleName}});if(!role)role=await prisma.role.create({data:{name:p.roleName}});const count=await prisma.staff.count();const user=await prisma.user.create({data:{email:p.email,firstName:p.firstName,lastName:p.lastName,phone:p.phone,officeId:p.officeId,passwordHash:await bcrypt.hash('ChangeMe123!',12),roles:{create:{roleId:role.id}}}});const staff=await prisma.staff.create({data:{staffNo:`WDS-${String(count+1).padStart(5,'0')}`,userId:user.id,officeId:p.officeId,title:p.title,department:p.department}});await audit(req,'CREATE','Staff',staff.id,undefined,{staffNo:staff.staffNo,email:p.email});res.status(201).json(staff)});

r.post('/volunteers',permit('staff.write'),async(req,res)=>{const p=z.object({firstName:z.string(),lastName:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional(),skills:z.array(z.string()).default([]),officeId:z.string().optional()}).parse(req.body);const x=await prisma.volunteer.create({data:p});await audit(req,'CREATE','Volunteer',x.id);res.status(201).json(x)});

r.get('/budgets',permit('finance.read'),async(_,res)=>res.json(await prisma.budget.findMany({include:{office:true},orderBy:[{year:'desc'},{name:'asc'}]})));
r.post('/budgets',permit('finance.write'),async(req,res)=>{const p=z.object({officeId:z.string(),name:z.string(),year:z.coerce.number().int(),amount:z.coerce.number().positive(),currency:z.string().default('USD')}).parse(req.body);const x=await prisma.budget.create({data:p});await audit(req,'CREATE','Budget',x.id);res.status(201).json(x)});
r.post('/expenses/:id/approve',permit('finance.write'),async(req,res)=>{const expense=await prisma.expense.update({where:{id:req.params.id},data:{status:'APPROVED'}});await prisma.ledgerEntry.upsert({where:{expenseId:expense.id},update:{},create:{type:'EXPENSE',amount:expense.amount,currency:expense.currency,account:expense.category,reference:expense.id,description:expense.description,expenseId:expense.id}});await audit(req,'APPROVE','Expense',expense.id);res.json(expense)});

r.get('/media',permit('communications.read'),async(_,res)=>res.json(await prisma.mediaAsset.findMany({orderBy:{createdAt:'desc'}})));
r.post('/media',permit('communications.write'),async(req,res)=>{const p=z.object({title:z.string(),type:z.string(),url:z.string().url(),language:z.string().default('so')}).parse(req.body);const x=await prisma.mediaAsset.create({data:{...p,createdById:req.user?.id}});await audit(req,'CREATE','MediaAsset',x.id);res.status(201).json(x)});
r.post('/communications/:id/approve',permit('communications.write'),async(req,res)=>{const x=await prisma.communicationCampaign.update({where:{id:req.params.id},data:{status:'ACTIVE'}});await audit(req,'APPROVE','CommunicationCampaign',x.id);res.json(x)});

r.get('/documents',permit('organisation.read'),async(_,res)=>res.json(await prisma.document.findMany({orderBy:{createdAt:'desc'}})));
r.post('/documents',permit('organisation.write'),async(req,res)=>{const p=z.object({title:z.string(),category:z.string(),url:z.string().url(),confidential:z.boolean().default(false),officeId:z.string().optional()}).parse(req.body);const x=await prisma.document.create({data:p});await audit(req,'CREATE','Document',x.id);res.status(201).json(x)});

r.get('/privacy-requests',permit('security.read'),async(_,res)=>res.json(await prisma.privacyRequest.findMany({orderBy:{createdAt:'desc'}})));
r.post('/privacy-requests',async(req,res)=>{const p=z.object({subjectType:z.string(),subjectId:z.string(),type:z.enum(['ACCESS','CORRECTION','DELETE','EXPORT','WITHDRAW_CONSENT']),notes:z.string().optional()}).parse(req.body);const x=await prisma.privacyRequest.create({data:p});await audit(req,'CREATE','PrivacyRequest',x.id);res.status(201).json(x)});

r.get('/conversations',async(req,res)=>res.json(await prisma.conversation.findMany({where:{members:{some:{userId:req.user!.id}}},include:{messages:{take:1,orderBy:{createdAt:'desc'}}},orderBy:{createdAt:'desc'}})));
r.post('/conversations',async(req,res)=>{const p=z.object({name:z.string().optional(),type:z.string().default('GROUP'),officeId:z.string().optional(),memberIds:z.array(z.string()).default([])}).parse(req.body);const ids=[...new Set([req.user!.id,...p.memberIds])];const x=await prisma.conversation.create({data:{name:p.name,type:p.type,officeId:p.officeId,members:{create:ids.map(userId=>({userId}))}}});await audit(req,'CREATE','Conversation',x.id);res.status(201).json(x)});
r.get('/conversations/:id/messages',async(req,res)=>{const allowed=await prisma.conversationMember.findUnique({where:{conversationId_userId:{conversationId:req.params.id,userId:req.user!.id}}});if(!allowed)return res.status(403).json({error:'Forbidden'});res.json(await prisma.message.findMany({where:{conversationId:req.params.id},orderBy:{createdAt:'asc'},take:500}))});
r.post('/conversations/:id/messages',async(req,res)=>{const allowed=await prisma.conversationMember.findUnique({where:{conversationId_userId:{conversationId:req.params.id,userId:req.user!.id}}});if(!allowed)return res.status(403).json({error:'Forbidden'});const p=z.object({kind:z.enum(['TEXT','VOICE','IMAGE','VIDEO','DOCUMENT']).default('TEXT'),body:z.string().optional(),attachmentUrl:z.string().url().optional()}).parse(req.body);const x=await prisma.message.create({data:{conversationId:req.params.id,senderId:req.user!.id,...p}});res.status(201).json(x)});

export default r;
