import{useEffect,useState}from'react';import{api}from'../lib/api';import{Card,Empty,Table}from'../components/Common';

type Cfg={title:string;subtitle:string;endpoint:string;headers:string[];row:(x:any)=>(string|number)[];form?:{label:string;key:string;type?:string}[]};
const cfgs:Record<string,Cfg>={
 organisation:{title:'Organisation & Worldwide Offices',subtitle:'Manage Somaliland and international office hierarchy.',endpoint:'/offices',headers:['Office','Type','Country','City','Status'],row:x=>[x.name,x.type,x.country,x.city||'—',x.active?'Active':'Inactive'],form:[{label:'Office name',key:'name'},{label:'Type',key:'type'},{label:'Country',key:'country'},{label:'City',key:'city'}]},
 members:{title:'Membership & Digital Membership',subtitle:'Register, approve and manage official party members.',endpoint:'/members',headers:['Member No.','Name','Country','Type','Status'],row:x=>[x.membershipNo,`${x.firstName} ${x.lastName}`,x.country,x.membershipType,x.status],form:[{label:'First name',key:'firstName'},{label:'Last name',key:'lastName'},{label:'Country',key:'country'},{label:'City',key:'city'},{label:'Membership type',key:'membershipType'}]},
 supporters:{title:'Global Supporters & Consent',subtitle:'Consent-based supporter registration and communication preferences.',endpoint:'/supporters',headers:['Name','Country','City','Consents','Status'],row:x=>[`${x.firstName} ${x.lastName||''}`.trim(),x.country,x.city||'—',(x.consents||[]).filter((c:any)=>c.granted).map((c:any)=>c.type).join(', ')||'None',x.status],form:[{label:'First name',key:'firstName'},{label:'Last name',key:'lastName'},{label:'Country',key:'country'},{label:'City',key:'city'}]},
 fundraising:{title:'Fundraising & Donations',subtitle:'Campaign creation, approvals, payments and reconciliation.',endpoint:'/fundraising',headers:['Campaign','Target','Raised','Status','Office'],row:x=>[x.title,`${x.currency} ${Number(x.targetAmount).toLocaleString()}`,`${x.currency} ${Number(x.raisedAmount).toLocaleString()}`,x.status,x.office?.name||'HQ'],form:[{label:'Title',key:'title'},{label:'Description',key:'description'},{label:'Target amount',key:'targetAmount',type:'number'},{label:'Currency',key:'currency'}]},
 finance:{title:'Finance, Budgets & Reconciliation',subtitle:'Track office expenditure, approvals and ledger reconciliation.',endpoint:'/expenses',headers:['Category','Description','Amount','Office','Status'],row:x=>[x.category,x.description,`${x.currency} ${Number(x.amount).toLocaleString()}`,x.office?.name||'—',x.status]},
 communications:{title:'Communications & Media Centre',subtitle:'Create authorised public communications with approval workflow.',endpoint:'/communications',headers:['Title','Channel','Audience','Status','Created'],row:x=>[x.title,x.channel,x.audience,x.status,new Date(x.createdAt).toLocaleDateString()],form:[{label:'Title',key:'title'},{label:'Channel',key:'channel'},{label:'Audience',key:'audience'},{label:'Message',key:'message'}]},
 operations:{title:'Events, Meetings & Tasks',subtitle:'Coordinate events, attendance, operational tasks and branch execution.',endpoint:'/events',headers:['Event','Venue','Starts','Capacity','Status'],row:x=>[x.title,x.venue||'—',new Date(x.startsAt).toLocaleString(),x.capacity||'—',x.status],form:[{label:'Event title',key:'title'},{label:'Venue',key:'venue'},{label:'Starts at',key:'startsAt',type:'datetime-local'},{label:'Capacity',key:'capacity',type:'number'}]},
 security:{title:'Security, Permissions & Audit',subtitle:'Review immutable operational audit history and privacy controls.',endpoint:'/audit',headers:['Time','Actor','Action','Entity','IP'],row:x=>[new Date(x.createdAt).toLocaleString(),x.actor?`${x.actor.firstName} ${x.actor.lastName}`:'System',x.action,x.entity,x.ip||'—']}
};
export function ModulePage({kind}:{kind:keyof typeof cfgs}){const c=cfgs[kind];const[data,setData]=useState<any[]>([]);const[open,setOpen]=useState(false);const[form,setForm]=useState<any>({});const[err,setErr]=useState('');const load=()=>{api(c.endpoint).then(setData).catch((e:any)=>setErr(e.message))};useEffect(()=>{load()},[c.endpoint]);const submit=async()=>{try{let payload={...form};if(kind==='organisation'&&!payload.type)payload.type='LOCAL';if(kind==='supporters')payload.consents=['NEWS','EVENTS'];await api(c.endpoint,{method:'POST',body:JSON.stringify(payload)});setOpen(false);setForm({});load()}catch(e:any){setErr(e.message)}};return <><div className="pageTitle"><div><h2>{c.title}</h2><p>{c.subtitle}</p></div>{c.form&&<button onClick={()=>setOpen(!open)}>+ Add new</button>}</div>{open&&<Card title="Create record"><div className="formGrid">{c.form!.map(f=><label key={f.key}><span>{f.label}</span><input type={f.type||'text'} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/></label>)}</div><button className="primary" onClick={submit}>Save</button></Card>}{err&&<div className="error">{err}</div>}<Card title={`${data.length} records`}>{data.length?<Table headers={c.headers} rows={data.map(c.row)}/>:<Empty text="No records yet"/>}</Card></>}

export function PeoplePage(){const[staff,setStaff]=useState<any[]>([]);const[vol,setVol]=useState<any[]>([]);useEffect(()=>{api('/staff').then(setStaff);api('/volunteers').then(setVol)},[]);return <><div className="pageTitle"><div><h2>Staff, Officials & Volunteers</h2><p>Role-linked staffing and volunteer operations across offices.</p></div></div><div className="grid2"><Card title="Staff"><Table headers={['Staff No.','Name','Title','Department','Office']} rows={staff.map(x=>[x.staffNo,`${x.user.firstName} ${x.user.lastName}`,x.title,x.department,x.office?.name||'—'])}/></Card><Card title="Volunteers"><Table headers={['Name','Skills','Office','Status']} rows={vol.map(x=>[`${x.firstName} ${x.lastName||''}`,x.skills.join(', '),x.office?.name||'—',x.status])}/></Card></div></>}

export function AnalyticsPage(){const[d,setD]=useState<any>();useEffect(()=>{api('/analytics/dashboard').then(setD)},[]);if(!d)return <div className="loading">Loading analytics…</div>;return <><div className="pageTitle"><div><h2>Leadership Analytics</h2><p>Aggregate organisational performance without individual political persuasion scoring.</p></div></div><div className="stats"><div className="stat"><small>Members</small><strong>{d.members}</strong></div><div className="stat"><small>Supporters</small><strong>{d.supporters}</strong></div><div className="stat"><small>Offices</small><strong>{d.offices}</strong></div><div className="stat"><small>Volunteers</small><strong>{d.volunteers}</strong></div></div><Card title="Country distribution"><Table headers={['Country','Supporters']} rows={d.supportersByCountry.map((x:any)=>[x.country,x.count])}/></Card></>}
